/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projectplanner;

import projectplanner.date.*;
import projectplanner.primitives.*;
import java.io.PrintStream;

public class ProjectCalculator {

    public static void main(String[] args){

        PrintStream out = System.out;

        Member simon = new Member(new Name("Simon"));
        Member thomas = new Member(new Name("Thomas"));
        Member jens = new Member(new Name("Jens"));
        Member gerd = new Member(new Name("Gerd"));
        Member kathrin = new Member(new Name("Kathrin"));
        Member christoph = new Member(new Name("Christoph"));
        Member jessica = new Member(new Name("Jessica"));
        Member sina = new Member(new Name("Sina"));
        Member markus = new Member(new Name("Markus"));

        Member[] hamburg_member = {simon,thomas,jens,gerd,kathrin,christoph,jessica,sina};
        Identifier hamburg_ident = new Identifier(new DateDay(29,10,2017),new Name("Städtereise Hamburg"));
        Project hamburg_project = new Project(hamburg_ident,hamburg_member);

        Member[] roommates = {markus,thomas,christoph};
        Identifier wg_ident = new Identifier(new DateMonth(10,2017), new Name("WG"));
        Project wg = new Project(wg_ident,roommates);

        Identifier miete_ident = new Identifier(new DateDay(1,10,2017),new Name("Miete"));
        MemberPayment miete_christoph = new MemberPayment(christoph, new Money(1275.80));
        Receipt miete_receipt = new Receipt(new MemberPayment[]{miete_christoph});
        wg.addActivity(miete_ident,roommates,miete_receipt);

        Identifier internet_ident = new Identifier(new DateDay(2,10,2017),new Name("Internet"));
        MemberPayment internet_markus = new MemberPayment(markus, new Money(29.99));
        Receipt internet_receipt = new Receipt(new MemberPayment[]{internet_markus});
        wg.addActivity(internet_ident,roommates,internet_receipt);

        Identifier bier_ident = new Identifier(new DateDay(3,10,2017),new Name("Bier"));
        MemberPayment bier_thomas = new MemberPayment(thomas, new Money(63.80));
        Receipt bier_receipt = new Receipt(new MemberPayment[]{bier_thomas});
        Member[] bier_member = new Member[]{thomas,christoph};
        wg.addActivity(bier_ident, bier_member,bier_receipt);

        Identifier kuehlschrank_ident = new Identifier(new DateDay(4,10,2017),new Name("kuehlschrank"));
        MemberPayment kuehlschrank_thomas = new MemberPayment(thomas, new Money(104.88));
        Receipt kuehlschrank_receipt = new Receipt(new MemberPayment[]{kuehlschrank_thomas});
        wg.addActivity(kuehlschrank_ident,roommates,kuehlschrank_receipt);

        Identifier stadtrundfahrt_ident = new Identifier(new DateDay(30,10,2017),new Name("stadtrundfahrt"));
        MemberPayment stadtrundfahrt_jens = new MemberPayment(jens, new Money(148.0));
        Receipt stadtrundfahrt_receipt = new Receipt(new MemberPayment[]{stadtrundfahrt_jens});
        hamburg_project.addActivity(stadtrundfahrt_ident,hamburg_member,stadtrundfahrt_receipt);

        Identifier musical_ident = new Identifier(new DateDay(31,10,2017),new Name("musical"));
        MemberPayment musical_sina = new MemberPayment(sina, new Money(500.0));
        MemberPayment musical_kathrin = new MemberPayment(kathrin, new Money(364.50));
        Receipt musical_receipt = new Receipt(new MemberPayment[]{musical_sina,musical_kathrin});
        Member[] musical_member = {gerd,kathrin,christoph,jessica,sina};
        hamburg_project.addActivity(musical_ident,musical_member,musical_receipt);

        Identifier bier_hamburg_ident = new Identifier(new DateDay(31,10,2017),new Name("bier_hamburg"));
        MemberPayment bier_hamburg_thomas = new MemberPayment(thomas, new Money(66.0));
        Receipt bier_hamburg_receipt = new Receipt(new MemberPayment[]{bier_hamburg_thomas});
        Member[] bier_hamburg_member = {thomas,jens,gerd,kathrin,christoph,jessica,sina};
        hamburg_project.addActivity(bier_hamburg_ident,bier_hamburg_member,bier_hamburg_receipt);

        Identifier mitfahrt_gerd_ident = new Identifier(new DateDay(1,11,2017),new Name("mitfahrt_gerd"));
        MemberPayment mitfahrt_gerd_gerd = new MemberPayment(gerd, new Money(61.38));
        Receipt mitfahrt_gerd_receipt = new Receipt(new MemberPayment[]{mitfahrt_gerd_gerd});
        Member[] mitfahrt_gerd_member = {gerd,jens,kathrin,sina,christoph};
        hamburg_project.addActivity(mitfahrt_gerd_ident,mitfahrt_gerd_member,mitfahrt_gerd_receipt);

        Identifier mitfahrt_simon_ident = new Identifier(new DateDay(1,11,2017),new Name("mitfahrt_simon"));
        MemberPayment mitfahrt_simon_simon = new MemberPayment(simon, new Money(54.43));
        Receipt mitfahrt_simon_receipt = new Receipt(new MemberPayment[]{mitfahrt_simon_simon});
        Member[] mitfahrt_simon_member = {simon,thomas,jessica};
        hamburg_project.addActivity(mitfahrt_simon_ident,mitfahrt_simon_member,mitfahrt_simon_receipt);

        hamburg_project.print(out);

        wg.print(out);

        wg_ident = new Identifier(new DateMonth(11,2017), new Name("WG"));
        wg = new Project(wg_ident,roommates);

        miete_ident = new Identifier(new DateDay(1,11,2017),new Name("Miete"));
        wg.addActivity(miete_ident,roommates,miete_receipt);

        internet_ident = new Identifier(new DateDay(2,11,2017),new Name("Internet"));
        wg.addActivity(internet_ident,roommates,internet_receipt);

        wg.print(out);

    }
}
